export const paths = [
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Big",
      "account": "300K",
      "avatar": "The Daredevil",
      "addOns" : ["14-Day Payout", "Double Leverage", "90/10 Profit Split", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Aggressive",
      "six": "Modest",
      "account": "200K",
      "avatar": "Master Trader",
      "addOns": ["14-Day Payout", "Double Leverage", "Reduce Profit Target to 8%", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Big",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Aggressive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Genius Trader",
      "addOns": ["14-Day Payout", "90/10 Profit Split", "No Minimum Trading Days"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "High",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "The Thinker", 
      "addOns": ["Double Leverage","Reduce Profit Target to 8%"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "Experienced",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "100K",
      "avatar": "Zen Trader",
      "addOns": ["Reduce Profit Target to 8%", "90/10 Profit Split"]
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Long",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Long",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Short",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Short",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": false,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Big",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    },
    {
      "one": "New",
      "two": "Weekends",
      "three": true,
      "four": "Low",
      "five": "Passive",
      "six": "Modest",
      "account": "50K",
      "avatar": "The Trailblazer",
      "addOns": "90/10 Profit Split"
    }
  ]
  